#!/bin/bash

set -e

# Workaround postrm when folder is missing
mkdir -p /etc/opt/chrome/native-messaging-hosts /etc/opt/chrome/policies/managed

rm -f /etc/opt/chrome/native-messaging-hosts/ee.nortal.sign-mass.json
rm -f /etc/opt/chrome/policies/managed/ee.nortal.sign_mass.chrome-token-signing.policy.json
rmdir -p --ignore-fail-on-non-empty /etc/opt/chrome/native-messaging-hosts
rmdir -p --ignore-fail-on-non-empty /etc/opt/chrome/policies/managed

#DEBHELPER#
